#!/usr/bin/env python3
"""Mount Isaac Sim's RealSense D455 stack at Klara's URDF camera frame.

Isaac Sim 6 does not provide a D435if asset.  Its certified D455 asset is used
as the closest built-in approximation and is referenced below the imported
``head_camera_link``.  The D455 asset keeps its own housing geometry, stereo
baseline, calibrated cameras, and depth-sensor schemas.  The overlapping
``tophead6`` visual meshes are removed from the Isaac USD during configuration.
An ActionGraph publishes its color image, depth image, camera calibration, and
depth-derived point cloud through the Isaac ROS 2 bridge.

Run this after ``import_klara.py`` with Isaac Sim's Python launcher::

    ~/isaacsim/python.sh assets/usd/configure_realsense.py

The default mount transform is identity so the sensor is coincident with
``head_camera_link``.  Optional local offsets can still be supplied for
visual/mechanical fine-tuning::

    ~/isaacsim/python.sh assets/usd/configure_realsense.py \
        --translation 0 0 0 --rotation-deg 0 0 0
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path


DEFAULT_USD = Path(__file__).resolve().with_name("klara.usd")

# Exact path generated by assets/usd/import_klara.py from xlerobot.urdf.
HEAD_CAMERA_LINK = (
    "/xlerobot/Geometry/world/chassis/top_base_link/head_pan_link/"
    "head_tilt_link/head_camera_link"
)
HEAD_TILT_LINK = HEAD_CAMERA_LINK.rsplit("/", 1)[0]
TOPHEAD6_LINK = f"{HEAD_TILT_LINK}/head_tilt_link_geom_1"
ARTICULATION_ROOT = "/xlerobot/Geometry/world/chassis"
MOUNT_PRIM = f"{HEAD_CAMERA_LINK}/realsense_mount"
SENSOR_ROOT = f"{MOUNT_PRIM}/realsense_d455"
D455_BODY = f"{SENSOR_ROOT}/RSD455"
COLOR_CAMERA = f"{D455_BODY}/Camera_OmniVision_OV9782_Color"
DEPTH_CAMERA = f"{D455_BODY}/Camera_Pseudo_Depth"
ROS_GRAPH = "/xlerobot/Graphs/realsense_ros2"

# Isaac Sim 6 has no D435/D435if built-in asset.  D455 is the nearest
# RealSense stereo depth-camera stack available through its sensor registry.
D455_ASSET_PATH = "/Isaac/Sensors/RealSense/D455/rsd455.usd"
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_RATE_HZ = 6.0

COLOR_IMAGE_TOPIC = "/camera/color/image_raw"
COLOR_INFO_TOPIC = "/camera/color/camera_info"
DEPTH_IMAGE_TOPIC = "/camera/depth/image_rect_raw"
DEPTH_INFO_TOPIC = "/camera/depth/camera_info"
POINTCLOUD_TOPIC = "/camera/depth/points"
COLOR_FRAME = "camera_color_optical_frame"
DEPTH_FRAME = "camera_depth_optical_frame"
CAMERA_LINK_FRAME = "camera_link"
COLOR_BODY_FRAME = "camera_color_frame"
DEPTH_BODY_FRAME = "camera_depth_frame"
BASE_FRAME = "base_link"
CHASSIS_FRAME = "chassis"
HEAD_CAMERA_FRAME = "head_camera_link"
HEAD_TILT_FRAME = "head_tilt_link"

# The referenced D455 asset puts its color imager 11.5 mm to the right of the
# pseudo-depth imager.  In the ROS body convention (+X forward, +Y left, +Z
# up), right is -Y.  This becomes +X in each optical frame.
CAMERA_LINK_TO_COLOR_TRANSLATION_M = (0.0, -0.0115, 0.0)

# Standard ROS body-frame -> optical-frame rotation, expressed as quaternion
# (x, y, z, w).  The D455 asset's internal 180-degree housing rotation makes
# its pseudo-depth camera coincide with this convention at the mount.
BODY_TO_OPTICAL_ROTATION = (-0.5, 0.5, -0.5, 0.5)

REQUIRED_EXTENSIONS = (
    "isaacsim.core.nodes",
    "isaacsim.ros2.bridge",
    "omni.graph.nodes",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Reference Isaac Sim's RealSense D455 sensor stack at Klara's "
            "head_camera_link."
        )
    )
    parser.add_argument(
        "--usd",
        type=Path,
        default=DEFAULT_USD,
        help=f"USD to update (default: {DEFAULT_USD})",
    )
    parser.add_argument(
        "--translation",
        type=float,
        nargs=3,
        metavar=("X", "Y", "Z"),
        default=(0.0, 0.0, 0.0),
        help="local mount translation in metres (default: 0 0 0)",
    )
    parser.add_argument(
        "--rotation-deg",
        type=float,
        nargs=3,
        metavar=("ROLL", "PITCH", "YAW"),
        default=(0.0, 0.0, 0.0),
        help="local mount XYZ rotation in degrees (default: 0 0 0)",
    )
    parser.add_argument(
        "--windowed",
        action="store_true",
        help="show the Isaac Sim window while configuring (headless by default)",
    )
    return parser.parse_args()


def require_prim(stage: object, path: str) -> object:
    prim = stage.GetPrimAtPath(path)
    if not prim.IsValid():
        raise RuntimeError(f"required USD prim is missing: {path}")
    return prim


def remove_tophead6_visual(stage: object) -> list[str]:
    """Remove tophead6's render meshes but preserve its imported fixed link.

    The separate ``head_tilt_link_geom_1`` link has no collision geometry and
    exists only to carry the tophead6 visual.  Keeping the empty link avoids
    leaving its imported fixed joint with a missing body.
    """
    from pxr import Usd, UsdGeom

    tophead6_link = require_prim(stage, TOPHEAD6_LINK)
    mesh_paths = [
        str(prim.GetPath())
        for prim in Usd.PrimRange(tophead6_link)
        if prim.IsA(UsdGeom.Mesh)
    ]
    for mesh_path in sorted(mesh_paths, key=len, reverse=True):
        stage.RemovePrim(mesh_path)
    return mesh_paths


def create_mount(
    stage: object,
    translation: tuple[float, ...],
    rotation: tuple[float, ...],
) -> None:
    from pxr import Gf, Sdf, UsdGeom

    require_prim(stage, HEAD_CAMERA_LINK)
    if stage.GetPrimAtPath(MOUNT_PRIM).IsValid():
        # The script owns this narrowly scoped subtree.  Rebuilding it makes
        # reruns deterministic and prevents duplicate referenced sensors.
        stage.RemovePrim(MOUNT_PRIM)

    mount = UsdGeom.Xform.Define(stage, MOUNT_PRIM)
    mount.AddTranslateOp().Set(Gf.Vec3d(*translation))
    mount.AddRotateXYZOp().Set(Gf.Vec3f(*rotation))
    mount.GetPrim().CreateAttribute(
        "isaac:nameOverride",
        Sdf.ValueTypeNames.String,
        custom=True,
    ).Set(CAMERA_LINK_FRAME)


def add_d455_asset(stage: object) -> str:
    from isaacsim.storage.native import get_assets_root_path
    from pxr import UsdGeom

    # Do not make configuration depend on a renderer, GPU, or an asset-server
    # health check.  Isaac resolves this reference when the stage is opened in
    # the normal simulator environment.
    assets_root = get_assets_root_path(skip_check=True)
    if not assets_root:
        raise RuntimeError("Isaac Sim assets root is unavailable")
    asset_url = assets_root.rstrip("/") + D455_ASSET_PATH

    # Isaac's sensor menu ultimately adds this same USD reference.  Keeping it
    # as a reference preserves the complete housing, calibrated camera prims,
    # stereo baseline, RenderProducts, and depth-sensor API schemas.
    sensor_root = UsdGeom.Xform.Define(stage, SENSOR_ROOT).GetPrim()
    sensor_root.GetReferences().AddReference(asset_url)
    return asset_url


def attach_d455_to_mount(stage: object) -> None:
    """Disable the asset's free rigid body so it follows head_camera_link."""
    from pxr import Sdf

    # The stock D455 authors RSD455 as a dynamic rigid body.  A transform
    # parent does not weld a dynamic body to the robot during simulation.
    # This local override turns it back into mounted geometry without editing
    # NVIDIA's referenced asset.
    body = stage.OverridePrim(D455_BODY)
    body.CreateAttribute(
        "physics:rigidBodyEnabled",
        Sdf.ValueTypeNames.Bool,
        custom=False,
    ).Set(False)


def configure_camera_rates(stage: object) -> None:
    """Match the 6 Hz stream rate used by the physical-camera configuration."""
    from pxr import Sdf

    for camera_path in (COLOR_CAMERA, DEPTH_CAMERA):
        camera = stage.OverridePrim(camera_path)
        camera.CreateAttribute(
            "omni:sensor:tickRate",
            Sdf.ValueTypeNames.Float,
            custom=False,
        ).Set(CAMERA_RATE_HZ)


def configure_ros_graph(stage: object) -> None:
    """Publish D455 data, simulation time, and a connected ROS 2 TF tree."""
    import omni.graph.core as og
    from pxr import Gf, Sdf, UsdGeom

    # head_camera_link is a massless URDF frame, so Isaac's articulation TF
    # expansion does not include it.  Read its fixed transform directly from
    # the imported USD and bridge the gap from the last rigid head link.
    head_camera_xform = Gf.Transform(
        UsdGeom.Xformable(require_prim(stage, HEAD_CAMERA_LINK)).GetLocalTransformation()
    )
    head_camera_translation = tuple(head_camera_xform.GetTranslation())
    head_camera_quat = head_camera_xform.GetRotation().GetQuat()
    head_camera_rotation = (
        *tuple(head_camera_quat.GetImaginary()),
        head_camera_quat.GetReal(),
    )

    if stage.GetPrimAtPath(ROS_GRAPH).IsValid():
        stage.RemovePrim(ROS_GRAPH)

    keys = og.Controller.Keys
    og.Controller.edit(
        {"graph_path": ROS_GRAPH, "evaluator_name": "execution"},
        {
            keys.CREATE_NODES: [
                ("OnPlaybackTick", "omni.graph.action.OnPlaybackTick"),
                ("ReadSimulationTime", "isaacsim.core.nodes.IsaacReadSimulationTime"),
                ("Context", "isaacsim.ros2.bridge.ROS2Context"),
                ("ClockPublisher", "isaacsim.ros2.bridge.ROS2PublishClock"),
                ("RobotTfCompute", "isaacsim.core.nodes.IsaacComputeTransformTree"),
                ("RobotTfPublisher", "isaacsim.ros2.bridge.ROS2PublishTransformTree"),
                (
                    "CameraMountTfCompute",
                    "isaacsim.core.nodes.IsaacComputeTransformTree",
                ),
                (
                    "CameraMountTfPublisher",
                    "isaacsim.ros2.bridge.ROS2PublishTransformTree",
                ),
                (
                    "ChassisToBaseTfPublisher",
                    "isaacsim.ros2.bridge.ROS2PublishRawTransformTree",
                ),
                (
                    "HeadTiltToHeadCameraTfPublisher",
                    "isaacsim.ros2.bridge.ROS2PublishRawTransformTree",
                ),
                (
                    "CameraToDepthTfPublisher",
                    "isaacsim.ros2.bridge.ROS2PublishRawTransformTree",
                ),
                (
                    "DepthOpticalTfPublisher",
                    "isaacsim.ros2.bridge.ROS2PublishRawTransformTree",
                ),
                (
                    "CameraToColorTfPublisher",
                    "isaacsim.ros2.bridge.ROS2PublishRawTransformTree",
                ),
                (
                    "ColorOpticalTfPublisher",
                    "isaacsim.ros2.bridge.ROS2PublishRawTransformTree",
                ),
                ("ColorRenderProduct", "isaacsim.core.nodes.IsaacCreateRenderProduct"),
                ("DepthRenderProduct", "isaacsim.core.nodes.IsaacCreateRenderProduct"),
                ("ColorImagePublisher", "isaacsim.ros2.bridge.ROS2CameraHelper"),
                ("ColorInfoPublisher", "isaacsim.ros2.bridge.ROS2CameraInfoHelper"),
                ("DepthImagePublisher", "isaacsim.ros2.bridge.ROS2CameraHelper"),
                ("DepthInfoPublisher", "isaacsim.ros2.bridge.ROS2CameraInfoHelper"),
                ("PointCloudPublisher", "isaacsim.ros2.bridge.ROS2CameraHelper"),
            ],
            keys.SET_VALUES: [
                ("ClockPublisher.inputs:topicName", "/clock"),
                (
                    "RobotTfCompute.inputs:targetPrims",
                    [Sdf.Path(ARTICULATION_ROOT)],
                ),
                ("RobotTfPublisher.inputs:topicName", "/tf"),
                (
                    "CameraMountTfCompute.inputs:targetPrims",
                    [Sdf.Path(MOUNT_PRIM)],
                ),
                (
                    "CameraMountTfCompute.inputs:parentPrim",
                    [Sdf.Path(HEAD_CAMERA_LINK)],
                ),
                ("CameraMountTfPublisher.inputs:topicName", "/tf"),
                ("ChassisToBaseTfPublisher.inputs:topicName", "/tf_static"),
                ("ChassisToBaseTfPublisher.inputs:staticPublisher", True),
                ("ChassisToBaseTfPublisher.inputs:parentFrameId", CHASSIS_FRAME),
                ("ChassisToBaseTfPublisher.inputs:childFrameId", BASE_FRAME),
                ("ChassisToBaseTfPublisher.inputs:translation", (0.0, 0.0, 0.0)),
                ("ChassisToBaseTfPublisher.inputs:rotation", (0.0, 0.0, 0.0, 1.0)),
                ("HeadTiltToHeadCameraTfPublisher.inputs:topicName", "/tf_static"),
                ("HeadTiltToHeadCameraTfPublisher.inputs:staticPublisher", True),
                (
                    "HeadTiltToHeadCameraTfPublisher.inputs:parentFrameId",
                    HEAD_TILT_FRAME,
                ),
                (
                    "HeadTiltToHeadCameraTfPublisher.inputs:childFrameId",
                    HEAD_CAMERA_FRAME,
                ),
                (
                    "HeadTiltToHeadCameraTfPublisher.inputs:translation",
                    head_camera_translation,
                ),
                (
                    "HeadTiltToHeadCameraTfPublisher.inputs:rotation",
                    head_camera_rotation,
                ),
                ("CameraToDepthTfPublisher.inputs:topicName", "/tf_static"),
                ("CameraToDepthTfPublisher.inputs:staticPublisher", True),
                ("CameraToDepthTfPublisher.inputs:parentFrameId", CAMERA_LINK_FRAME),
                ("CameraToDepthTfPublisher.inputs:childFrameId", DEPTH_BODY_FRAME),
                ("CameraToDepthTfPublisher.inputs:translation", (0.0, 0.0, 0.0)),
                ("CameraToDepthTfPublisher.inputs:rotation", (0.0, 0.0, 0.0, 1.0)),
                ("DepthOpticalTfPublisher.inputs:topicName", "/tf_static"),
                ("DepthOpticalTfPublisher.inputs:staticPublisher", True),
                ("DepthOpticalTfPublisher.inputs:parentFrameId", DEPTH_BODY_FRAME),
                ("DepthOpticalTfPublisher.inputs:childFrameId", DEPTH_FRAME),
                ("DepthOpticalTfPublisher.inputs:translation", (0.0, 0.0, 0.0)),
                ("DepthOpticalTfPublisher.inputs:rotation", BODY_TO_OPTICAL_ROTATION),
                ("CameraToColorTfPublisher.inputs:topicName", "/tf_static"),
                ("CameraToColorTfPublisher.inputs:staticPublisher", True),
                ("CameraToColorTfPublisher.inputs:parentFrameId", CAMERA_LINK_FRAME),
                ("CameraToColorTfPublisher.inputs:childFrameId", COLOR_BODY_FRAME),
                (
                    "CameraToColorTfPublisher.inputs:translation",
                    CAMERA_LINK_TO_COLOR_TRANSLATION_M,
                ),
                ("CameraToColorTfPublisher.inputs:rotation", (0.0, 0.0, 0.0, 1.0)),
                ("ColorOpticalTfPublisher.inputs:topicName", "/tf_static"),
                ("ColorOpticalTfPublisher.inputs:staticPublisher", True),
                ("ColorOpticalTfPublisher.inputs:parentFrameId", COLOR_BODY_FRAME),
                ("ColorOpticalTfPublisher.inputs:childFrameId", COLOR_FRAME),
                ("ColorOpticalTfPublisher.inputs:translation", (0.0, 0.0, 0.0)),
                ("ColorOpticalTfPublisher.inputs:rotation", BODY_TO_OPTICAL_ROTATION),
                ("ColorRenderProduct.inputs:cameraPrim", [Sdf.Path(COLOR_CAMERA)]),
                ("ColorRenderProduct.inputs:width", CAMERA_WIDTH),
                ("ColorRenderProduct.inputs:height", CAMERA_HEIGHT),
                ("DepthRenderProduct.inputs:cameraPrim", [Sdf.Path(DEPTH_CAMERA)]),
                ("DepthRenderProduct.inputs:width", CAMERA_WIDTH),
                ("DepthRenderProduct.inputs:height", CAMERA_HEIGHT),
                ("ColorImagePublisher.inputs:topicName", COLOR_IMAGE_TOPIC),
                ("ColorImagePublisher.inputs:type", "rgb"),
                ("ColorImagePublisher.inputs:frameId", COLOR_FRAME),
                ("ColorInfoPublisher.inputs:topicName", COLOR_INFO_TOPIC),
                ("ColorInfoPublisher.inputs:frameId", COLOR_FRAME),
                ("DepthImagePublisher.inputs:topicName", DEPTH_IMAGE_TOPIC),
                ("DepthImagePublisher.inputs:type", "depth"),
                ("DepthImagePublisher.inputs:frameId", DEPTH_FRAME),
                ("DepthInfoPublisher.inputs:topicName", DEPTH_INFO_TOPIC),
                ("DepthInfoPublisher.inputs:frameId", DEPTH_FRAME),
                ("PointCloudPublisher.inputs:topicName", POINTCLOUD_TOPIC),
                ("PointCloudPublisher.inputs:type", "depth_pcl"),
                ("PointCloudPublisher.inputs:frameId", DEPTH_FRAME),
            ],
            keys.CONNECT: [
                ("OnPlaybackTick.outputs:tick", "ClockPublisher.inputs:execIn"),
                ("OnPlaybackTick.outputs:tick", "RobotTfCompute.inputs:execIn"),
                ("RobotTfCompute.outputs:execOut", "RobotTfPublisher.inputs:execIn"),
                (
                    "RobotTfCompute.outputs:parentFrames",
                    "RobotTfPublisher.inputs:parentFrames",
                ),
                (
                    "RobotTfCompute.outputs:childFrames",
                    "RobotTfPublisher.inputs:childFrames",
                ),
                (
                    "RobotTfCompute.outputs:translations",
                    "RobotTfPublisher.inputs:translations",
                ),
                (
                    "RobotTfCompute.outputs:orientations",
                    "RobotTfPublisher.inputs:orientations",
                ),
                (
                    "OnPlaybackTick.outputs:tick",
                    "CameraMountTfCompute.inputs:execIn",
                ),
                (
                    "CameraMountTfCompute.outputs:execOut",
                    "CameraMountTfPublisher.inputs:execIn",
                ),
                (
                    "CameraMountTfCompute.outputs:parentFrames",
                    "CameraMountTfPublisher.inputs:parentFrames",
                ),
                (
                    "CameraMountTfCompute.outputs:childFrames",
                    "CameraMountTfPublisher.inputs:childFrames",
                ),
                (
                    "CameraMountTfCompute.outputs:translations",
                    "CameraMountTfPublisher.inputs:translations",
                ),
                (
                    "CameraMountTfCompute.outputs:orientations",
                    "CameraMountTfPublisher.inputs:orientations",
                ),
                (
                    "OnPlaybackTick.outputs:tick",
                    "ChassisToBaseTfPublisher.inputs:execIn",
                ),
                (
                    "OnPlaybackTick.outputs:tick",
                    "HeadTiltToHeadCameraTfPublisher.inputs:execIn",
                ),
                (
                    "OnPlaybackTick.outputs:tick",
                    "CameraToDepthTfPublisher.inputs:execIn",
                ),
                (
                    "OnPlaybackTick.outputs:tick",
                    "DepthOpticalTfPublisher.inputs:execIn",
                ),
                (
                    "OnPlaybackTick.outputs:tick",
                    "CameraToColorTfPublisher.inputs:execIn",
                ),
                (
                    "OnPlaybackTick.outputs:tick",
                    "ColorOpticalTfPublisher.inputs:execIn",
                ),
                (
                    "ReadSimulationTime.outputs:simulationTime",
                    "ClockPublisher.inputs:timeStamp",
                ),
                (
                    "ReadSimulationTime.outputs:simulationTime",
                    "RobotTfPublisher.inputs:timeStamp",
                ),
                (
                    "ReadSimulationTime.outputs:simulationTime",
                    "CameraMountTfPublisher.inputs:timeStamp",
                ),
                (
                    "ReadSimulationTime.outputs:simulationTime",
                    "ChassisToBaseTfPublisher.inputs:timeStamp",
                ),
                (
                    "ReadSimulationTime.outputs:simulationTime",
                    "HeadTiltToHeadCameraTfPublisher.inputs:timeStamp",
                ),
                (
                    "ReadSimulationTime.outputs:simulationTime",
                    "CameraToDepthTfPublisher.inputs:timeStamp",
                ),
                (
                    "ReadSimulationTime.outputs:simulationTime",
                    "DepthOpticalTfPublisher.inputs:timeStamp",
                ),
                (
                    "ReadSimulationTime.outputs:simulationTime",
                    "CameraToColorTfPublisher.inputs:timeStamp",
                ),
                (
                    "ReadSimulationTime.outputs:simulationTime",
                    "ColorOpticalTfPublisher.inputs:timeStamp",
                ),
                ("OnPlaybackTick.outputs:tick", "ColorRenderProduct.inputs:execIn"),
                ("OnPlaybackTick.outputs:tick", "DepthRenderProduct.inputs:execIn"),
                ("ColorRenderProduct.outputs:execOut", "ColorImagePublisher.inputs:execIn"),
                ("ColorRenderProduct.outputs:execOut", "ColorInfoPublisher.inputs:execIn"),
                ("DepthRenderProduct.outputs:execOut", "DepthImagePublisher.inputs:execIn"),
                ("DepthRenderProduct.outputs:execOut", "DepthInfoPublisher.inputs:execIn"),
                ("DepthRenderProduct.outputs:execOut", "PointCloudPublisher.inputs:execIn"),
                (
                    "ColorRenderProduct.outputs:renderProductPath",
                    "ColorImagePublisher.inputs:renderProductPath",
                ),
                (
                    "ColorRenderProduct.outputs:renderProductPath",
                    "ColorInfoPublisher.inputs:renderProductPath",
                ),
                (
                    "DepthRenderProduct.outputs:renderProductPath",
                    "DepthImagePublisher.inputs:renderProductPath",
                ),
                (
                    "DepthRenderProduct.outputs:renderProductPath",
                    "DepthInfoPublisher.inputs:renderProductPath",
                ),
                (
                    "DepthRenderProduct.outputs:renderProductPath",
                    "PointCloudPublisher.inputs:renderProductPath",
                ),
                ("Context.outputs:context", "ColorImagePublisher.inputs:context"),
                ("Context.outputs:context", "ColorInfoPublisher.inputs:context"),
                ("Context.outputs:context", "DepthImagePublisher.inputs:context"),
                ("Context.outputs:context", "DepthInfoPublisher.inputs:context"),
                ("Context.outputs:context", "PointCloudPublisher.inputs:context"),
                ("Context.outputs:context", "ClockPublisher.inputs:context"),
                ("Context.outputs:context", "RobotTfPublisher.inputs:context"),
                ("Context.outputs:context", "CameraMountTfPublisher.inputs:context"),
                (
                    "Context.outputs:context",
                    "ChassisToBaseTfPublisher.inputs:context",
                ),
                (
                    "Context.outputs:context",
                    "HeadTiltToHeadCameraTfPublisher.inputs:context",
                ),
                (
                    "Context.outputs:context",
                    "CameraToDepthTfPublisher.inputs:context",
                ),
                (
                    "Context.outputs:context",
                    "DepthOpticalTfPublisher.inputs:context",
                ),
                (
                    "Context.outputs:context",
                    "CameraToColorTfPublisher.inputs:context",
                ),
                (
                    "Context.outputs:context",
                    "ColorOpticalTfPublisher.inputs:context",
                ),
            ],
        },
    )


def export_stage_atomically(stage: object, usd_path: Path) -> None:
    original_mode = usd_path.stat().st_mode & 0o777
    with tempfile.NamedTemporaryFile(
        dir=usd_path.parent,
        prefix=f".{usd_path.stem}.",
        suffix=usd_path.suffix,
        delete=False,
    ) as temporary_output:
        temporary_path = Path(temporary_output.name)
    try:
        if not stage.GetRootLayer().Export(str(temporary_path)):
            raise RuntimeError(f"failed to export configured USD to {temporary_path}")
        temporary_path.chmod(original_mode)
        os.replace(temporary_path, usd_path)
    finally:
        temporary_path.unlink(missing_ok=True)


def configure_usd(
    usd_path: Path,
    translation: tuple[float, ...],
    rotation: tuple[float, ...],
    windowed: bool,
) -> None:
    if not usd_path.is_file():
        raise ValueError(f"USD does not exist: {usd_path}")

    try:
        from isaacsim.simulation_app import SimulationApp
    except ModuleNotFoundError as error:
        raise RuntimeError(
            "Isaac Sim is not available. Run this script with Isaac Sim's ./python.sh."
        ) from error

    simulation_app = SimulationApp({"headless": not windowed})
    try:
        import omni.kit.app
        import omni.usd

        extension_manager = omni.kit.app.get_app().get_extension_manager()
        for extension in REQUIRED_EXTENSIONS:
            if not extension_manager.is_extension_enabled(extension):
                extension_manager.set_extension_enabled_immediate(extension, True)
                simulation_app.update()

        context = omni.usd.get_context()
        if not context.open_stage(str(usd_path)):
            raise RuntimeError(f"Isaac Sim could not open USD: {usd_path}")
        simulation_app.update()
        stage = context.get_stage()
        if stage is None:
            raise RuntimeError(f"Isaac Sim did not create a stage for: {usd_path}")

        removed_tophead6_meshes = remove_tophead6_visual(stage)
        create_mount(stage, translation, rotation)
        asset_url = add_d455_asset(stage)
        attach_d455_to_mount(stage)
        configure_camera_rates(stage)
        configure_ros_graph(stage)
        export_stage_atomically(stage, usd_path)

        print(f"Mounted Isaac Sim RealSense D455 in {usd_path}", flush=True)
        print(f"URDF frame: {HEAD_CAMERA_LINK}", flush=True)
        print(f"Sensor root: {SENSOR_ROOT}", flush=True)
        print(f"Asset: {asset_url}", flush=True)
        print(f"Attached body override: {D455_BODY} rigidBodyEnabled=false", flush=True)
        print(
            f"ROS 2 camera graph: {ROS_GRAPH}; {CAMERA_WIDTH}x{CAMERA_HEIGHT} "
            f"at {CAMERA_RATE_HZ:g} Hz",
            flush=True,
        )
        print(f"  {COLOR_IMAGE_TOPIC}", flush=True)
        print(f"  {COLOR_INFO_TOPIC}", flush=True)
        print(f"  {DEPTH_IMAGE_TOPIC}", flush=True)
        print(f"  {DEPTH_INFO_TOPIC}", flush=True)
        print(f"  {POINTCLOUD_TOPIC}", flush=True)
        print("  /clock", flush=True)
        print("  /tf (articulation and live camera mount)", flush=True)
        print("  /tf_static (base, head-camera, and RealSense frames)", flush=True)
        print(
            f"Removed tophead6 visual meshes: {len(removed_tophead6_meshes)}",
            flush=True,
        )
        print(
            f"Local mount: translation={tuple(translation)} m, "
            f"rotation_xyz={tuple(rotation)} deg",
            flush=True,
        )
    finally:
        simulation_app.close()


def main() -> int:
    args = parse_args()
    usd_path = args.usd.expanduser().resolve()
    try:
        configure_usd(
            usd_path,
            tuple(args.translation),
            tuple(args.rotation_deg),
            args.windowed,
        )
    except (RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
